In [ ]:
Consider a die is thrown 600 times with following results.

observed = [115, 47, 41, 101, 210, 96]

Is the die unbiased at 10% significance level?


In [13]:
import numpy as np
from scipy.stats import chi2
observed = np.array([115, 47, 41, 201, 110, 96])# Observed frequencies
expected = np.array([100, 100, 100, 100, 100, 100])# Expected frequencies (assuming a fair die)
chi2_stat = np.sum((observed - expected)**2 / expected)# Calculate chi-square statistic
df = len(observed) - 1  # Degrees of freedom (number of categories - 1)
# Critical value for 10% significance level
critical_value = chi2.ppf(0.90, df)
p_value = 1 - chi2.cdf(chi2_stat, df)# p-value
print(f"Chi-squared Statistic: {chi2_stat}")
print(f"Critical Value at 10% significance level: {critical_value}")
print(f"p-value: {p_value}")
if chi2_stat < critical_value:
    print("Fail to reject the null hypothesis: The die is unbiased.")
else:
    print("Reject the null hypothesis: The die is biased.")


Chi-squared Statistic: 186.32000000000002
Critical Value at 10% significance level: 9.236356899781123
p-value: 0.0
Reject the null hypothesis: The die is biased.


In [ ]:
question: specification. A pin may meet the specification, or it may be too thin or too thick. 
Pins are sampled from each machine, and the number of pins in each category is counted.
Table below presents the results. Use the data in Table to test the null hypothesis that the proportions of pins that are
too thin, OK, or too thick are the same for all the machines.
Table

data = np.array([
    [10, 102, 8],   # Machine 1
    [34, 161, 5],   # Machine 2
    [12, 79, 9],    # Machine 3
    [10, 60, 10]    # Machine 4
])

In [2]:
import numpy as np
import pandas as pd
from scipy.stats import chi2
from scipy.stats import chi2_contingency
# Define the observed data
data = np.array([
    [10, 102, 8],   # Machine 1
    [34, 161, 5],   # Machine 2
    [12, 79, 9],    # Machine 3
    [10, 60, 10]    # Machine 4
])
# Create a DataFrame for better visualization (optional)
df = pd.DataFrame(data, columns=['Too Thin', 'OK', 'Too Thick'], 
                  index=['Machine 1', 'Machine 2', 'Machine 3', 'Machine 4'])
print("Observed Data:\n", df)
chi2_stat, p_value, dof, expected = chi2_contingency(data)# Perform the Chi-Square test
print("\nChi-Square Statistic:", chi2_stat)
print("P-Value:", p_value)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)
alpha = 0.05
if chi2_stat > chi2.ppf(1 - alpha, dof):
    print("Reject the null hypothesis: There is a significant difference.")
else:
    print("Fail to reject the null hypothesis: No significant difference.")


Observed Data:
            Too Thin   OK  Too Thick
Machine 1        10  102          8
Machine 2        34  161          5
Machine 3        12   79          9
Machine 4        10   60         10

Chi-Square Statistic: 15.584353328056686
P-Value: 0.01616760116149423
Degrees of Freedom: 6
Expected Frequencies:
 [[ 15.84  96.48   7.68]
 [ 26.4  160.8   12.8 ]
 [ 13.2   80.4    6.4 ]
 [ 10.56  64.32   5.12]]
Reject the null hypothesis: There is a significant difference.


In [ ]:
Chi-Square Test and Test of Independence, Analyzing the relationship between gender and preference for a product purchase

In [17]:
import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency
import matplotlib.pyplot as plt

# Create a contingency table
data = np.array([[30, 10],  # Male
                 [20, 30]]) # Female

# Display the contingency table as a DataFrame for clarity
contingency_table = pd.DataFrame(data, 
                                  columns=['Purchased', 'Not Purchased'], 
                                  index=['Male', 'Female'])
print("Contingency Table:\n", contingency_table)

# Perform the Chi-Square test
chi2_stat, p_value, dof, expected = chi2_contingency(data)

# Display results
print("\nChi-Square Statistic:", chi2_stat)
print("P-Value:", p_value)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

# Determine significance level
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant association between gender and product preference.")
else:
    print("Fail to reject the null hypothesis: No significant association between gender and product preference.")


Contingency Table:
         Purchased  Not Purchased
Male           30             10
Female         20             30

Chi-Square Statistic: 9.6530625
P-Value: 0.001890361677058677
Degrees of Freedom: 1
Expected Frequencies:
 [[22.22222222 17.77777778]
 [27.77777778 22.22222222]]
Reject the null hypothesis: There is a significant association between gender and product preference.


In [ ]:
using Chi-Square Test, Analyzing the association between vaccination and recovery of the patients considering COVID data.

In [16]:
import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency
import matplotlib.pyplot as plt
# Create a contingency table
data = np.array([[10, 30],    # Vaccinated
                 [10, 40]])   # Not Vaccinated
# Display the contingency table as a DataFrame for clarity
contingency_table = pd.DataFrame(data, 
                                  columns=['Recovered', 'Not Recovered'], 
                                  index=['Vaccinated', 'Not Vaccinated'])
print("Contingency Table:\n", contingency_table)
# Perform the Chi-Square test
chi2_stat, p_value, dof, expected = chi2_contingency(data)
# Display results
print("\nChi-Square Statistic:", chi2_stat)
print("P-Value:", p_value)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)
# Determine significance level
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant association between vaccination and recovery.")
else:
    print("Fail to reject the null hypothesis: No significant association between vaccination and recovery.")



Contingency Table:
                 Recovered  Not Recovered
Vaccinated             10             30
Not Vaccinated         10             40

Chi-Square Statistic: 0.09723214285714282
P-Value: 0.7551767989558744
Degrees of Freedom: 1
Expected Frequencies:
 [[ 8.88888889 31.11111111]
 [11.11111111 38.88888889]]
Fail to reject the null hypothesis: No significant association between vaccination and recovery.
